"""Render the seven business definitions directly from the authoritative YAML."""
from lab.query import ROOT,catalog
lines=['# Metric catalog','', 'Generated by `make parse` from `models/semantic.yml`. '
       'See [modeling decisions](semantics.md) for time, coverage and null policies.','']
for name,metric in catalog().items():
    meta=metric['config']['meta']
    if meta['diagnostic']:
        continue
    lines += [f"## {metric['label']} (`{name}`)",'',metric['description'],'',
              f"- Grain: {meta['grain']}",f"- Units: {meta['units']}",
              f"- Owner: {meta['owner']}",f"- Synonyms: {', '.join(meta['synonyms'])}",
              f"- Certification: {meta['certification']}",'']
(ROOT/'docs/metrics.md').write_text('\n'.join(lines))
